// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiLink.Data.Context;

#nullable disable

namespace TaxiLink.Data.Migrations
{
    [DbContext(typeof(DBContextTaxiLink))]
    [Migration("20260319214202_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiLink.Domain.Models.AdditionalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPercentage = false,
                            Name = "Дитяче крісло",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            IsPercentage = true,
                            Name = "Чайові",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            IsPercentage = false,
                            Name = "Допомога з багажем",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            IsPercentage = false,
                            Name = "Провезення тварини",
                            Price = 20m
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BlockedUserId")
                        .HasColumnType("int");

                    b.Property<int>("BlockerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerUserId");

                    b.ToTable("Blacklists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockedAt = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            BlockedUserId = 3,
                            BlockerUserId = 2
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.CancellationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CancellationReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Клієнт передумав"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Водій запізнився"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Інша причина"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Помилкове замовлення"
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Київ",
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Житомир",
                            PriceMultiplier = 0.8m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Черняхів",
                            PriceMultiplier = 0.7m
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcceptanceRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iban")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFopActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkingMode")
                        .HasColumnType("bit");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WalletBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptanceRate = 98.5m,
                            CommissionRate = 12.5m,
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iban = "UA123456789012345678901234567",
                            IsFopActive = true,
                            IsVerified = true,
                            IsWorkingMode = true,
                            Patronymic = "Петрович",
                            ReferralCode = "IVAN2026",
                            TaxId = "1234567890",
                            UserId = 3,
                            WalletBalance = 1500.25m
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Знижено ціни",
                            ImagePath = "/img/tariffs.png",
                            PublishedAt = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Оновлення тарифів"
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancellationReasonId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClientComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ClientPriceBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Distance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassengerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleClassId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancellationReasonId");

                    b.HasIndex("CityId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleClassId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ClientComment = "Буду з валізою",
                            ClientPriceBonus = 5m,
                            CompletedAt = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 3, 19, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 5.2m,
                            DriverId = 1,
                            DropoffAddress = "Залізничний вокзал",
                            OrderStatusId = 3,
                            PassengerName = "Даша",
                            PassengerPhone = "+380991234567",
                            PaymentMethodId = 2,
                            PickupAddress = "вул. Хрещатик, 22",
                            PromoCodeId = 1,
                            TotalPrice = 180.50m,
                            UserId = 2,
                            VehicleClassId = 2,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.OrderAdditionalService", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalServiceId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "AdditionalServiceId");

                    b.HasIndex("AdditionalServiceId");

                    b.ToTable("OrderAdditionalServices");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AdditionalServiceId = 1
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Очікується"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В дорозі"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Завершено"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Скасовано"
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Готівка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Картка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Водію на картку"
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "START2026",
                            CurrentUses = 0,
                            DiscountPercentage = 15m,
                            ExpiryDate = new DateTime(2026, 4, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxUses = 100
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Дуже швидка поїздка на Renault!",
                            CreatedAt = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Driver"
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.SavedAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressText = "вул. Хрещатик, 22",
                            Title = "Дім",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("BonusBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DefaultCityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PrefersNoMusic")
                        .HasColumnType("bit");

                    b.Property<bool>("PrefersSilentRide")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rating")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCityId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusBalance = 0m,
                            Email = "admin@taxilink.com",
                            FirstName = "Олена",
                            LastName = "Диспетчер",
                            PasswordHash = "admin",
                            PhoneNumber = "+380000000001",
                            PrefersNoMusic = false,
                            PrefersSilentRide = false,
                            Rating = 0m,
                            RegistrationDate = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "/img/client_dasha.png",
                            BonusBalance = 150.5m,
                            DefaultCityId = 1,
                            Email = "dasha@gmail.com",
                            FirstName = "Дарія",
                            GoogleId = "gl_222",
                            LastName = "Лемеха",
                            PasswordHash = "123",
                            PhoneNumber = "+380991234567",
                            PrefersNoMusic = true,
                            PrefersSilentRide = true,
                            Rating = 5.0m,
                            RegistrationDate = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "/img/ivan_driver.png",
                            BonusBalance = 0m,
                            DefaultCityId = 2,
                            Email = "ivan@mail.com",
                            FacebookId = "fb_333",
                            FirstName = "Іван",
                            LastName = "Водій",
                            PasswordHash = "driver",
                            PhoneNumber = "+380671234567",
                            PrefersNoMusic = false,
                            PrefersSilentRide = false,
                            Rating = 4.8m,
                            RegistrationDate = new DateTime(2026, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.UserPaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardMask")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardMask = "4149********1234",
                            IsDefault = true,
                            PaymentSystem = "Visa",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PassengerSeats")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Renault",
                            Color = "Білий",
                            DriverId = 1,
                            InsuranceExpiryDate = new DateTime(2027, 3, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            LicensePlate = "AA1234BC",
                            Model = "Clio 4",
                            PassengerSeats = 4,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleAdditionalService", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalServiceId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "AdditionalServiceId");

                    b.HasIndex("AdditionalServiceId");

                    b.ToTable("VehicleAdditionalServices");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            AdditionalServiceId = 1
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CancellationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerKmOutsideCity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerMinuteWaiting")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("VehicleClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 50m,
                            CancellationFee = 30m,
                            Description = "Базовий рівень",
                            Name = "Економ",
                            PricePerKm = 10m,
                            PricePerKmOutsideCity = 15m,
                            PricePerMinuteWaiting = 2m
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 80m,
                            CancellationFee = 50m,
                            Description = "Авто з кондиціонером",
                            Name = "Комфорт",
                            PricePerKm = 15m,
                            PricePerKmOutsideCity = 20m,
                            PricePerMinuteWaiting = 3m
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehiclePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehiclePhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoPath = "/img/renault_clio.png",
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleVehicleClass", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleClassId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "VehicleClassId");

                    b.HasIndex("VehicleClassId");

                    b.ToTable("VehicleVehicleClasses");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            VehicleClassId = 2
                        });
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Blacklist", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.User", "BlockedUser")
                        .WithMany("BlockedMe")
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.User", "BlockerUser")
                        .WithMany("BlockedByMe")
                        .HasForeignKey("BlockerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("BlockerUser");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Driver", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Order", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.CancellationReason", "CancellationReason")
                        .WithMany("Orders")
                        .HasForeignKey("CancellationReasonId");

                    b.HasOne("TaxiLink.Domain.Models.City", "City")
                        .WithMany("Orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxiLink.Domain.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.PromoCode", "PromoCode")
                        .WithMany("Orders")
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("TaxiLink.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.VehicleClass", "VehicleClass")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleId");

                    b.Navigation("CancellationReason");

                    b.Navigation("City");

                    b.Navigation("Driver");

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PromoCode");

                    b.Navigation("User");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleClass");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.OrderAdditionalService", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.AdditionalService", "AdditionalService")
                        .WithMany("OrderAdditionalServices")
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.Order", "Order")
                        .WithMany("OrderAdditionalServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalService");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Review", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("TaxiLink.Domain.Models.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.SavedAddress", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.User", "User")
                        .WithMany("SavedAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.User", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.City", "DefaultCity")
                        .WithMany()
                        .HasForeignKey("DefaultCityId");

                    b.HasOne("TaxiLink.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultCity");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.UserPaymentCard", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.User", "User")
                        .WithMany("PaymentCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleAdditionalService", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.AdditionalService", "AdditionalService")
                        .WithMany("CapableVehicles")
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("ProvidedServices")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalService");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehiclePhoto", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("Photos")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleVehicleClass", b =>
                {
                    b.HasOne("TaxiLink.Domain.Models.VehicleClass", "VehicleClass")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiLink.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleClasses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleClass");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.AdditionalService", b =>
                {
                    b.Navigation("CapableVehicles");

                    b.Navigation("OrderAdditionalServices");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.CancellationReason", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.City", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Driver", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderAdditionalServices");

                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.PromoCode", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.User", b =>
                {
                    b.Navigation("BlockedByMe");

                    b.Navigation("BlockedMe");

                    b.Navigation("Orders");

                    b.Navigation("PaymentCards");

                    b.Navigation("SavedAddress");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.Vehicle", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Photos");

                    b.Navigation("ProvidedServices");

                    b.Navigation("VehicleClasses");
                });

            modelBuilder.Entity("TaxiLink.Domain.Models.VehicleClass", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
